import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'todo-input',
  template: `
 <div>
 <input [value]="title" 
        (keyup)="changeTitle($event.target.value)">

 <button (click)="changeTitle('Button Clicked!')">
 Save
 </button>
 </div> 

    
  `,
  styleUrls: ['./input.component.css']
})
export class InputComponent implements OnInit {
title: string = 'My First Todo Title!!!';
  constructor() { 
    console.log('in constructor');
    this.changeTitle('I love Angular');
    console.log(this.title)
  }

  ngOnInit() {
  setTimeout(() => {
    window.confirm('any text');
  }, 3000);
  }
  generateTitle(): string {
    return 'This title was generated by a method.';
  }
  changeTitle(newTitle: string): void {
    this.title = newTitle;
    console.log ('the title was changed', newTitle);

  } 


}
